name: Deploy to Firebase Admin portal on merge
on:
  push:
    branches:
      - develop
    paths:
      - "admin/**"

jobs:
  build-and-deploy-admin-portal:
    environment: development
    name: Build and deploy admin portal
    runs-on: ubuntu-latest
    env:
      working-directory: "/"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.working-directory }}/.nvmrc

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm ci

      - name: Build web app
        working-directory: ${{ env.working-directory }}
        run: npm run build
        env:
          VITE_FIREBASE_ENV: 'DEV'

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_GENERATOR_NEW_DEV }}"
          channelId: live
          projectId: test-generator-new-dev
          target: admin-dev
          entryPoint: ${{ env.working-directory }}
